// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.11.4
// source: ScheduleInstructionStep3V2.proto

package imburse_protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateTime_TimeSpanScale int32

const (
	DateTime_DAYS         DateTime_TimeSpanScale = 0
	DateTime_HOURS        DateTime_TimeSpanScale = 1
	DateTime_MINUTES      DateTime_TimeSpanScale = 2
	DateTime_SECONDS      DateTime_TimeSpanScale = 3
	DateTime_MILLISECONDS DateTime_TimeSpanScale = 4
	DateTime_TICKS        DateTime_TimeSpanScale = 5
	DateTime_MINMAX       DateTime_TimeSpanScale = 15 // dubious
)

// Enum value maps for DateTime_TimeSpanScale.
var (
	DateTime_TimeSpanScale_name = map[int32]string{
		0:  "DAYS",
		1:  "HOURS",
		2:  "MINUTES",
		3:  "SECONDS",
		4:  "MILLISECONDS",
		5:  "TICKS",
		15: "MINMAX",
	}
	DateTime_TimeSpanScale_value = map[string]int32{
		"DAYS":         0,
		"HOURS":        1,
		"MINUTES":      2,
		"SECONDS":      3,
		"MILLISECONDS": 4,
		"TICKS":        5,
		"MINMAX":       15,
	}
)

func (x DateTime_TimeSpanScale) Enum() *DateTime_TimeSpanScale {
	p := new(DateTime_TimeSpanScale)
	*p = x
	return p
}

func (x DateTime_TimeSpanScale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateTime_TimeSpanScale) Descriptor() protoreflect.EnumDescriptor {
	return file_ScheduleInstructionStep3V2_proto_enumTypes[0].Descriptor()
}

func (DateTime_TimeSpanScale) Type() protoreflect.EnumType {
	return &file_ScheduleInstructionStep3V2_proto_enumTypes[0]
}

func (x DateTime_TimeSpanScale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateTime_TimeSpanScale.Descriptor instead.
func (DateTime_TimeSpanScale) EnumDescriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{1, 0}
}

type DateTime_DateTimeKind int32

const (
	// The time represented is not specified as either local time or Coordinated Universal Time (UTC).
	DateTime_UNSPECIFIED DateTime_DateTimeKind = 0
	// The time represented is UTC.
	DateTime_UTC DateTime_DateTimeKind = 1
	// The time represented is local time.
	DateTime_LOCAL DateTime_DateTimeKind = 2
)

// Enum value maps for DateTime_DateTimeKind.
var (
	DateTime_DateTimeKind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UTC",
		2: "LOCAL",
	}
	DateTime_DateTimeKind_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UTC":         1,
		"LOCAL":       2,
	}
)

func (x DateTime_DateTimeKind) Enum() *DateTime_DateTimeKind {
	p := new(DateTime_DateTimeKind)
	*p = x
	return p
}

func (x DateTime_DateTimeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateTime_DateTimeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ScheduleInstructionStep3V2_proto_enumTypes[1].Descriptor()
}

func (DateTime_DateTimeKind) Type() protoreflect.EnumType {
	return &file_ScheduleInstructionStep3V2_proto_enumTypes[1]
}

func (x DateTime_DateTimeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateTime_DateTimeKind.Descriptor instead.
func (DateTime_DateTimeKind) EnumDescriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{1, 1}
}

type ScheduleInstructionStep3V2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId               string    `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	RequestId                   *Guid     `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	TenantId                    *Guid     `protobuf:"bytes,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	CustomerRef                 string    `protobuf:"bytes,4,opt,name=customerRef,proto3" json:"customerRef,omitempty"`
	FinancialInstrumentId       *Guid     `protobuf:"bytes,5,opt,name=financialInstrumentId,proto3" json:"financialInstrumentId,omitempty"`
	WorkflowId                  string    `protobuf:"bytes,6,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	OrderRef                    string    `protobuf:"bytes,7,opt,name=orderRef,proto3" json:"orderRef,omitempty"`
	InstructionRef              string    `protobuf:"bytes,8,opt,name=instructionRef,proto3" json:"instructionRef,omitempty"`
	Country                     string    `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Currency                    string    `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount                      *Decimal  `protobuf:"bytes,11,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestedSettlementDate     *DateTime `protobuf:"bytes,12,opt,name=requestedSettlementDate,proto3" json:"requestedSettlementDate,omitempty"`
	ForecastedSettlementDate    *DateTime `protobuf:"bytes,13,opt,name=forecastedSettlementDate,proto3" json:"forecastedSettlementDate,omitempty"`
	ScheduledExecutionTimestamp *DateTime `protobuf:"bytes,14,opt,name=scheduledExecutionTimestamp,proto3" json:"scheduledExecutionTimestamp,omitempty"`
	AppId                       string    `protobuf:"bytes,15,opt,name=appId,proto3" json:"appId,omitempty"`
	AppQueue                    string    `protobuf:"bytes,16,opt,name=appQueue,proto3" json:"appQueue,omitempty"`
	PaymentMethod               string    `protobuf:"bytes,17,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
}

func (x *ScheduleInstructionStep3V2) Reset() {
	*x = ScheduleInstructionStep3V2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleInstructionStep3V2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleInstructionStep3V2) ProtoMessage() {}

func (x *ScheduleInstructionStep3V2) ProtoReflect() protoreflect.Message {
	mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleInstructionStep3V2.ProtoReflect.Descriptor instead.
func (*ScheduleInstructionStep3V2) Descriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleInstructionStep3V2) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetRequestId() *Guid {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetTenantId() *Guid {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetCustomerRef() string {
	if x != nil {
		return x.CustomerRef
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetFinancialInstrumentId() *Guid {
	if x != nil {
		return x.FinancialInstrumentId
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetOrderRef() string {
	if x != nil {
		return x.OrderRef
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetInstructionRef() string {
	if x != nil {
		return x.InstructionRef
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetAmount() *Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetRequestedSettlementDate() *DateTime {
	if x != nil {
		return x.RequestedSettlementDate
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetForecastedSettlementDate() *DateTime {
	if x != nil {
		return x.ForecastedSettlementDate
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetScheduledExecutionTimestamp() *DateTime {
	if x != nil {
		return x.ScheduledExecutionTimestamp
	}
	return nil
}

func (x *ScheduleInstructionStep3V2) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetAppQueue() string {
	if x != nil {
		return x.AppQueue
	}
	return ""
}

func (x *ScheduleInstructionStep3V2) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type DateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64                  `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`                                   // the offset (in units of the selected scale) from 1970/01/01
	Scale DateTime_TimeSpanScale `protobuf:"varint,2,opt,name=scale,proto3,enum=imburse.DateTime_TimeSpanScale" json:"scale,omitempty"` // the scale of the timespan [default = DAYS]
	Kind  DateTime_DateTimeKind  `protobuf:"varint,3,opt,name=kind,proto3,enum=imburse.DateTime_DateTimeKind" json:"kind,omitempty"`    // the kind of date/time being represented [default = UNSPECIFIED]
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{1}
}

func (x *DateTime) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DateTime) GetScale() DateTime_TimeSpanScale {
	if x != nil {
		return x.Scale
	}
	return DateTime_DAYS
}

func (x *DateTime) GetKind() DateTime_DateTimeKind {
	if x != nil {
		return x.Kind
	}
	return DateTime_UNSPECIFIED
}

type Guid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lo uint64 `protobuf:"fixed64,1,opt,name=lo,proto3" json:"lo,omitempty"` // the first 8 bytes of the guid (note:crazy-endian)
	Hi uint64 `protobuf:"fixed64,2,opt,name=hi,proto3" json:"hi,omitempty"` // the second 8 bytes of the guid (note:crazy-endian)
}

func (x *Guid) Reset() {
	*x = Guid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guid) ProtoMessage() {}

func (x *Guid) ProtoReflect() protoreflect.Message {
	mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guid.ProtoReflect.Descriptor instead.
func (*Guid) Descriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{2}
}

func (x *Guid) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Guid) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

type Decimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lo        uint64 `protobuf:"varint,1,opt,name=lo,proto3" json:"lo,omitempty"`               // the first 64 bits of the underlying value
	Hi        uint32 `protobuf:"varint,2,opt,name=hi,proto3" json:"hi,omitempty"`               // the last 32 bis of the underlying value
	SignScale uint32 `protobuf:"varint,3,opt,name=signScale,proto3" json:"signScale,omitempty"` // the number of decimal digits (bits 1-16), and the sign (bit 0)
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_ScheduleInstructionStep3V2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_ScheduleInstructionStep3V2_proto_rawDescGZIP(), []int{3}
}

func (x *Decimal) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Decimal) GetHi() uint32 {
	if x != nil {
		return x.Hi
	}
	return 0
}

func (x *Decimal) GetSignScale() uint32 {
	if x != nil {
		return x.SignScale
	}
	return 0
}

var File_ScheduleInstructionStep3V2_proto protoreflect.FileDescriptor

var file_ScheduleInstructionStep3V2_proto_rawDesc = []byte{
	0x0a, 0x20, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x33, 0x56, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x22, 0x8e, 0x06, 0x0a, 0x1a,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x33, 0x56, 0x32, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x75,
	0x69, 0x64, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x29, 0x0a,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x66, 0x12, 0x43, 0x0a, 0x15, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6d, 0x62, 0x75,
	0x72, 0x73, 0x65, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x52, 0x15, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x12, 0x26, 0x0a, 0x0e, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6d, 0x62, 0x75,
	0x72, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x17, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x17, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x4d, 0x0a, 0x18, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x18, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x53, 0x0a, 0x1b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x1b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70,
	0x70, 0x51, 0x75, 0x65, 0x75, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70,
	0x70, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0xa9, 0x02, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x35, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x69, 0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x67, 0x0a, 0x0d, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x41, 0x59, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x49,
	0x4c, 0x4c, 0x49, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x49, 0x43, 0x4b, 0x53, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x49, 0x4e, 0x4d, 0x41,
	0x58, 0x10, 0x0f, 0x22, 0x33, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x54, 0x43, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x02, 0x22, 0x26, 0x0a, 0x04, 0x47, 0x75, 0x69, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x6c, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x68, 0x69,
	0x22, 0x47, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x6c, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x68,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x68, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x69,
	0x6d, 0x62, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ScheduleInstructionStep3V2_proto_rawDescOnce sync.Once
	file_ScheduleInstructionStep3V2_proto_rawDescData = file_ScheduleInstructionStep3V2_proto_rawDesc
)

func file_ScheduleInstructionStep3V2_proto_rawDescGZIP() []byte {
	file_ScheduleInstructionStep3V2_proto_rawDescOnce.Do(func() {
		file_ScheduleInstructionStep3V2_proto_rawDescData = protoimpl.X.CompressGZIP(file_ScheduleInstructionStep3V2_proto_rawDescData)
	})
	return file_ScheduleInstructionStep3V2_proto_rawDescData
}

var file_ScheduleInstructionStep3V2_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ScheduleInstructionStep3V2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ScheduleInstructionStep3V2_proto_goTypes = []interface{}{
	(DateTime_TimeSpanScale)(0),        // 0: imburse.DateTime.TimeSpanScale
	(DateTime_DateTimeKind)(0),         // 1: imburse.DateTime.DateTimeKind
	(*ScheduleInstructionStep3V2)(nil), // 2: imburse.ScheduleInstructionStep3V2
	(*DateTime)(nil),                   // 3: imburse.DateTime
	(*Guid)(nil),                       // 4: imburse.Guid
	(*Decimal)(nil),                    // 5: imburse.Decimal
}
var file_ScheduleInstructionStep3V2_proto_depIdxs = []int32{
	4, // 0: imburse.ScheduleInstructionStep3V2.requestId:type_name -> imburse.Guid
	4, // 1: imburse.ScheduleInstructionStep3V2.tenantId:type_name -> imburse.Guid
	4, // 2: imburse.ScheduleInstructionStep3V2.financialInstrumentId:type_name -> imburse.Guid
	5, // 3: imburse.ScheduleInstructionStep3V2.amount:type_name -> imburse.Decimal
	3, // 4: imburse.ScheduleInstructionStep3V2.requestedSettlementDate:type_name -> imburse.DateTime
	3, // 5: imburse.ScheduleInstructionStep3V2.forecastedSettlementDate:type_name -> imburse.DateTime
	3, // 6: imburse.ScheduleInstructionStep3V2.scheduledExecutionTimestamp:type_name -> imburse.DateTime
	0, // 7: imburse.DateTime.scale:type_name -> imburse.DateTime.TimeSpanScale
	1, // 8: imburse.DateTime.kind:type_name -> imburse.DateTime.DateTimeKind
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_ScheduleInstructionStep3V2_proto_init() }
func file_ScheduleInstructionStep3V2_proto_init() {
	if File_ScheduleInstructionStep3V2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ScheduleInstructionStep3V2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleInstructionStep3V2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ScheduleInstructionStep3V2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ScheduleInstructionStep3V2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ScheduleInstructionStep3V2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ScheduleInstructionStep3V2_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ScheduleInstructionStep3V2_proto_goTypes,
		DependencyIndexes: file_ScheduleInstructionStep3V2_proto_depIdxs,
		EnumInfos:         file_ScheduleInstructionStep3V2_proto_enumTypes,
		MessageInfos:      file_ScheduleInstructionStep3V2_proto_msgTypes,
	}.Build()
	File_ScheduleInstructionStep3V2_proto = out.File
	file_ScheduleInstructionStep3V2_proto_rawDesc = nil
	file_ScheduleInstructionStep3V2_proto_goTypes = nil
	file_ScheduleInstructionStep3V2_proto_depIdxs = nil
}
